FROM node:alpine
WORKDIR "/app"
COPY ./package.json ./
COPY ./package-lock.json ./
COPY ./nuxt.config.js ./
RUN npm install
COPY . .
ENV HOST=0.0.0.0
ENV API_URL=http://localhost
CMD ["npm", "run", "dev"]