sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t tennis/client -f ./client/Dockerfile.dev ./client

script:
  - docker run tennis/client npm run test


after_success:
  - docker build -t maniizu3110/tennis-client ./client
  - docker build -t maniizu3110/tennis-server ./server
  - docker build -t maniizu3110/tennis-nginx ./nginx
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push maniizu3110/tennis-client
  - docker push maniizu3110/tennis-server
  - docker push maniizu3110/tennis-nginx

deploy:
  provider: elasticbeanstalk
  region: 'ap-northeast-1'
  app: 'tennis'
  env: 'Tennis-env'
  bucket_name: 'elasticbeanstalk-ap-northeast-1-800317362310'
  bucket_path: 'tennis'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
