version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      # DBがないとエラーで繋がらないので先に作成しておく必要あり
      # - POSTGRES_DB=tennis
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/tennis?sslmode=disable
    depends_on:
      - postgres
    volumes:
      - ./server /app
  client:
    stdin_open: true
    ports:
    - "3000:3000"
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
