version: "3"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=tennis
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
      # TODO:フロントはフロントでローカルから接続できると嬉しい
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/tennis?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
  # client:
  #   build:
  #     dockerfile: Dockerfile.dev
